globs:
  - "**/*.md"
ignores:
  - "node_modules/**"
  - "**/node_modules/**"
  - "build/**"
  - "dist/**"
  - ".pulumi/**"
  - "CLAUDE.md"
  - ".github/ISSUE_TEMPLATE/**"
  - ".github/ISSUE_TEMPLATES/**"
  - ".github/PULL_REQUEST_TEMPLATE/**"
  - "@docs/**"
  - "docs/**"
  - "tests/**"
  - "**/AUDIT_*.md"
  - "**/PHASE_*.md"
  - "**/*_REPORT*.md"
  - "**/*INCIDENT*.md"
  - "**/*STATUS*.md"
  - "FUTURE_*.md"
  - "INFRASTRUCTURE_*.md"
  - "TAILSCALE_*.md"
  - ".venv/**"
  - "**/.venv/**"
  - ".pytest_cache/**"
  - "**/*_SUMMARY.md"
  - "**/*_RESULTS.md"
  - "**/*_FIX_*.md"
  - "**/*_PLAN*.md"
  - "**/*ARCHITECTURE*.md"
  - "**/*DEPLOYMENT*.md"
  - "**/*RECOVERY*.md"
  - "**/AGENTS.md"
  - "**/immutable-*.md"
