#!/usr/bin/env bash
# Verify SME deployment is working correctly

set -e

echo "=== SME Deployment Verification ==="
echo ""

# Color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check function
check() {
    local description="$1"
    local command="$2"

    echo -n "Checking $description... "

    if eval "$command" > /dev/null 2>&1; then
        echo -e "${GREEN}✓${NC}"
        return 0
    else
        echo -e "${RED}✗${NC}"
        return 1
    fi
}

# 1. Check DNS records
echo "1. DNS Configuration:"
check "label.boathou.se DNS" "nslookup label.boathou.se"
check "gpu.boathou.se DNS" "nslookup gpu.boathou.se"
check "k3s.boathou.se DNS" "nslookup k3s.boathou.se"
echo ""

# 2. Check Kubernetes resources
echo "2. Kubernetes Resources:"
check "Label Studio deployment" "kubectl get deployment label-studio -n apps -o name"
check "Adapter deployment" "kubectl get deployment ls-triton-adapter -n apps -o name"
check "Cloudflared deployment" "kubectl get deployment cloudflared -n cloudflared -o name"
echo ""

# 3. Check pod status
echo "3. Pod Status:"
LABEL_POD=$(kubectl get pods -n apps -l app=label-studio -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
ADAPTER_POD=$(kubectl get pods -n apps -l app=ls-triton-adapter -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

if [ -n "$LABEL_POD" ]; then
    STATUS=$(kubectl get pod "$LABEL_POD" -n apps -o jsonpath='{.status.phase}')
    if [ "$STATUS" = "Running" ]; then
        echo -e "Label Studio pod: ${GREEN}Running${NC}"
    else
        echo -e "Label Studio pod: ${RED}$STATUS${NC}"
    fi
fi

if [ -n "$ADAPTER_POD" ]; then
    STATUS=$(kubectl get pod "$ADAPTER_POD" -n apps -o jsonpath='{.status.phase}')
    if [ "$STATUS" = "Running" ]; then
        echo -e "Adapter pod: ${GREEN}Running${NC}"
    else
        echo -e "Adapter pod: ${RED}$STATUS${NC}"
    fi
fi
echo ""

# 4. Check HTTPS endpoints
echo "4. HTTPS Endpoints:"
echo -e "${YELLOW}Testing Label Studio...${NC}"
LABEL_STATUS=$(curl -sk -o /dev/null -w "%{http_code}" https://label.boathou.se/ || echo "000")
if [ "$LABEL_STATUS" = "200" ] || [ "$LABEL_STATUS" = "302" ] || [ "$LABEL_STATUS" = "403" ]; then
    echo -e "Label Studio (https://label.boathou.se): ${GREEN}Accessible (HTTP $LABEL_STATUS)${NC}"
else
    echo -e "Label Studio (https://label.boathou.se): ${RED}Error (HTTP $LABEL_STATUS)${NC}"
fi

echo -e "${YELLOW}Testing GPU service...${NC}"
GPU_STATUS=$(curl -sk -o /dev/null -w "%{http_code}" https://gpu.boathou.se/v2/health/ready || echo "000")
if [ "$GPU_STATUS" = "200" ]; then
    echo -e "GPU Service (https://gpu.boathou.se): ${GREEN}Healthy${NC}"
else
    echo -e "GPU Service (https://gpu.boathou.se): ${RED}Not Ready (HTTP $GPU_STATUS)${NC}"
fi
echo ""

# 5. Check Cloudflare tunnel logs for errors
echo "5. Recent Tunnel Logs:"
echo -e "${YELLOW}Checking for tunnel errors...${NC}"
ERRORS=$(kubectl logs -n cloudflared deployment/cloudflared --tail=20 2>/dev/null | grep -i error | wc -l)
if [ "$ERRORS" -eq 0 ]; then
    echo -e "Cloudflare tunnel: ${GREEN}No recent errors${NC}"
else
    echo -e "Cloudflare tunnel: ${YELLOW}$ERRORS error(s) in recent logs${NC}"
    echo "Run: kubectl logs -n cloudflared deployment/cloudflared --tail=50"
fi
echo ""

# 6. Test adapter health
echo "6. ML Adapter Health:"
kubectl port-forward -n apps svc/ls-triton-adapter 9090:9090 > /dev/null 2>&1 &
PF_PID=$!
sleep 2

ADAPTER_HEALTH=$(curl -s http://localhost:9090/health 2>/dev/null | jq -r '.ok' 2>/dev/null || echo "false")
if [ "$ADAPTER_HEALTH" = "true" ]; then
    echo -e "Adapter health check: ${GREEN}Healthy${NC}"
    NER_COUNT=$(curl -s http://localhost:9090/health 2>/dev/null | jq -r '.labels.count' 2>/dev/null || echo "0")
    echo "NER labels configured: $NER_COUNT"
else
    echo -e "Adapter health check: ${RED}Unhealthy${NC}"
fi

kill $PF_PID 2>/dev/null || true
echo ""

# Summary
echo "=== Summary ==="
echo ""
echo "Access URLs:"
echo "  Label Studio: https://label.boathou.se"
echo "  GPU Services: https://gpu.boathou.se"
echo "  K3s API: https://k3s.boathou.se"
echo ""
echo "If you see SSL warnings:"
echo "  1. The certificate will be auto-generated by Cloudflare"
echo "  2. Clear browser cache if issues persist"
echo ""
echo "For GPU tunnel errors (Error 1033):"
echo "  1. Ensure Calypso connector is deployed: make deploy-calypso"
echo "  2. Check node tunnel is running: ssh oceanid@192.168.2.80 'sudo systemctl status cloudflared-node'"
echo "  3. Verify Triton is running: ssh oceanid@192.168.2.80 'sudo systemctl status tritonserver'"
echo ""
