project:
  name: "Oceanid Infrastructure Cluster"
  description: "Talos Linux + k3s + Cloudflare Tunnels across multiple nodes"

nodes:
  - name: tethys
    type: hostinger-vps
    role: primary-control
    ip: TBD
    specs:
      cpu: TBD
      ram: TBD
      storage: TBD

  - name: styx
    type: hostinger-vps
    role: worker
    ip: TBD
    specs:
      cpu: TBD
      ram: TBD
      storage: TBD

  - name: meliae
    type: oracle-cloud
    role: worker
    ip: 140.238.138.35
    specs:
      cpu: 1 OCPU
      ram: 1GB
      storage: 47GB

  - name: poseidon
    type: local-workstation
    role: gpu-worker
    ip: local
    specs:
      cpu: AMD Ryzen
      ram: TBD
      gpu: RTX 4090
      storage: TBD

stack:
  os: Talos Linux
  orchestration: k3s
  iac: Pulumi
  secrets: Vault + 1Password Connect
  networking: Cloudflare Tunnels

services:
  management:
    - vault-1password-sync
    - pulumi-automation
    - cloudflared

  monitoring:
    - prometheus
    - grafana
    - loki

tasks:
  phase1_preparation:
    - ✅ Create Infrastructure vault in 1Password
    - ✅ Document meliae Oracle VPS
    - ✅ Prepare SSH keys
    - [ ] Get Hostinger VPS credentials and IPs
    - [ ] Prepare Talos configuration files
    - [ ] Generate k3s cluster tokens

  phase2_talos_installation:
    - [ ] Install Talos on tethys (Hostinger VPS 1)
    - [ ] Install Talos on styx (Hostinger VPS 2)
    - [ ] Install Talos on meliae (Oracle VPS)
    - [ ] Install Talos on poseidon (workstation)

  phase3_k3s_setup:
    - [ ] Initialize k3s control plane on tethys
    - [ ] Join styx as worker node
    - [ ] Join meliae as worker node
    - [ ] Join poseidon as GPU worker node
    - [ ] Configure GPU runtime for poseidon

  phase4_networking:
    - [ ] Set up Cloudflare Tunnel for cluster ingress
    - [ ] Configure internal service mesh
    - [ ] Set up DNS entries
    - [ ] Configure firewall rules (all ports closed)

  phase5_core_services:
    - [ ] Deploy Vault + 1Password Connect
    - [ ] Deploy Pulumi automation server
    - [ ] Configure secrets synchronization
    - [ ] Set up GitOps workflow

  phase6_documentation:
    - [ ] Document all nodes in Infrastructure vault
    - [ ] Create connection guides
    - [ ] Document emergency procedures
    - [ ] Create backup strategies