---
# Vault + 1Password Connect Deployment for k3s
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-credentials
  namespace: vault
type: Opaque
stringData:
  1password-credentials.json: |
    # Generate from 1Password Connect Server
    # op connect server create <server-name> --vaults Infrastructure
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-1password
  namespace: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault-1password
  template:
    metadata:
      labels:
        app: vault-1password
    spec:
      containers:
      # Vault Container
      - name: vault
        image: hashicorp/vault:latest
        ports:
        - containerPort: 8200
          name: vault
        env:
        - name: VAULT_ADDR
          value: "http://127.0.0.1:8200"
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        volumeMounts:
        - name: vault-data
          mountPath: /vault/file
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 100m
        securityContext:
          capabilities:
            add:
              - IPC_LOCK

      # 1Password Connect API
      - name: op-connect-api
        image: 1password/connect-api:latest
        ports:
        - containerPort: 8080
          name: connect-api
        volumeMounts:
        - name: op-credentials
          mountPath: /home/opuser/.op
        env:
        - name: OP_SESSION
          value: "/home/opuser/.op/1password-credentials.json"
        - name: OP_LOG_LEVEL
          value: "info"
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m

      # 1Password Connect Sync
      - name: op-connect-sync
        image: 1password/connect-sync:latest
        ports:
        - containerPort: 8081
          name: connect-sync
        volumeMounts:
        - name: op-credentials
          mountPath: /home/opuser/.op
        env:
        - name: OP_SESSION
          value: "/home/opuser/.op/1password-credentials.json"
        - name: OP_HTTP_PORT
          value: "8081"
        - name: OP_LOG_LEVEL
          value: "info"
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m

      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-data
      - name: op-credentials
        secret:
          secretName: onepassword-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: vault-1password
  namespace: vault
spec:
  selector:
    app: vault-1password
  ports:
  - name: vault
    port: 8200
    targetPort: 8200
  - name: connect-api
    port: 8080
    targetPort: 8080
  - name: connect-sync
    port: 8081
    targetPort: 8081