name: "docling_granite_python"
platform: "python"
max_batch_size: 0

input: [
  {
    name: "pdf_data"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  },
  {
    name: "prompt"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  },
  {
    name: "text"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  }
]

output: [
  {
    name: "response"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  }
]

instance_group: [
  { kind: KIND_GPU, gpus: [1] }
]

parameters: {
  key: "EXECUTION_ENV_PATH"
  value: { string_value: "/models/docling_granite_python/1" }
}
