---
# Redis for Argilla job queue
apiVersion: v1
kind: Service
metadata:
  name: argilla-redis
  namespace: apps
  labels:
    app: argilla-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: argilla-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argilla-redis
  namespace: apps
  labels:
    app: argilla-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argilla-redis
  template:
    metadata:
      labels:
        app: argilla-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5

---
# Elasticsearch for Argilla search engine
apiVersion: v1
kind: Service
metadata:
  name: argilla-elasticsearch
  namespace: apps
  labels:
    app: argilla-elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: http
  selector:
    app: argilla-elasticsearch

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argilla-elasticsearch
  namespace: apps
  labels:
    app: argilla-elasticsearch
spec:
  serviceName: argilla-elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: argilla-elasticsearch
  template:
    metadata:
      labels:
        app: argilla-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
          ports:
            - containerPort: 9200
              name: http
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

---
# PostgreSQL for Argilla workspace
apiVersion: v1
kind: Service
metadata:
  name: argilla-postgres
  namespace: apps
  labels:
    app: argilla-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: argilla-postgres

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argilla-postgres
  namespace: apps
  labels:
    app: argilla-postgres
spec:
  serviceName: argilla-postgres
  replicas: 1
  selector:
    matchLabels:
      app: argilla-postgres
  template:
    metadata:
      labels:
        app: argilla-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: argilla
            - name: POSTGRES_USER
              value: argilla
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - argilla
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - argilla
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

---
# Argilla Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argilla
  namespace: apps
  labels:
    app: argilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argilla
  template:
    metadata:
      labels:
        app: argilla
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: argilla
          image: argilla/argilla-server:v2.8.0
          command: ["/bin/bash", "-c"]
          args:
            - |
              export ARGILLA_DATABASE_URL="postgresql+asyncpg://${ARGILLA_DATABASE_USER}:${ARGILLA_DATABASE_PASSWORD}@${ARGILLA_DATABASE_HOST}:${ARGILLA_DATABASE_PORT}/${ARGILLA_DATABASE_NAME}"
              exec python -m argilla_server start
          ports:
            - containerPort: 6900
              name: http
          env:
            - name: ARGILLA_HOME_PATH
              value: /data
            # Elasticsearch connection
            - name: ARGILLA_ELASTICSEARCH
              value: http://argilla-elasticsearch:9200
            - name: ARGILLA_REDIS_URL
              value: redis://argilla-redis:6379/0
            # PostgreSQL connection components (used to construct DATABASE_URL)
            - name: ARGILLA_DATABASE_HOST
              value: argilla-postgres
            - name: ARGILLA_DATABASE_PORT
              value: "5432"
            - name: ARGILLA_DATABASE_NAME
              value: argilla
            - name: ARGILLA_DATABASE_USER
              value: argilla
            - name: ARGILLA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: POSTGRES_PASSWORD
            - name: ARGILLA_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: AUTH_SECRET_KEY
            # Default admin account
            - name: USERNAME
              value: "admin"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: ADMIN_PASSWORD
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: argilla-secrets
                  key: ADMIN_API_KEY
            - name: WORKSPACE
              value: "argilla"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 6900
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 6900
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: argilla
  namespace: apps
  labels:
    app: argilla
spec:
  type: ClusterIP
  ports:
    - port: 6900
      targetPort: 6900
      protocol: TCP
      name: http
  selector:
    app: argilla

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argilla-pdb
  namespace: apps
  labels:
    app: argilla
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: argilla
