# NOTE: Secrets are created by Pulumi from ESC for now
# Future: Migrate to SealedSecrets or SOPS for pure GitOps
# The secret 'labelstudio-db-credentials' must exist with:
# - POSTGRE_PASSWORD: password for labelfish_owner
# - DATABASE_URL: full postgresql:// connection string
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: label-studio
  namespace: apps
spec:
  interval: 10m
  chart:
    spec:
      chart: label-studio
      version: "1.11.4"
      sourceRef:
        kind: HelmRepository
        name: heartex
        namespace: flux-system
  values:
    global:
      pgConfig:
        host: p.3x4xvkn3xza2zjwiklcuonpamy.db.postgresbridge.com
        port: 5432
        dbName: labelfish
        userName: labelfish_owner
        password:
          secretName: label-studio-db-credentials
          secretKey: POSTGRE_PASSWORD
      extraEnvironmentVars:
        LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
        CSRF_TRUSTED_ORIGINS: "https://label.boathou.se"
        DJANGO_ALLOWED_HOSTS: "label.boathou.se"
        LABEL_STUDIO_HOST: "https://label.boathou.se"
      persistence:
        enabled: true
        type: s3
        config:
          s3:
            accessKeyExistingSecret: labelstudio-s3-credentials
            accessKeyExistingSecretKey: AWS_ACCESS_KEY_ID
            secretKeyExistingSecret: labelstudio-s3-credentials
            secretKeyExistingSecretKey: AWS_SECRET_ACCESS_KEY
            region: us-east-1
            bucket: labelstudio-goldfish-uploads
    app:
      image:
        tag: "1.21.0"  # Override chart default (1.20.0) to use latest version
      service:
        type: ClusterIP
        port: 8080
        targetPort: 8080
      resources: {}
      nodeSelector:
        kubernetes.io/hostname: srv712429  # Database only accessible from control plane
    postgresql:
      enabled: false
    redis:
      enabled: false
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: heartex
  namespace: flux-system
spec:
  interval: 10m
  url: https://charts.heartex.com
