apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-system
  labels:
    app.kubernetes.io/name: pulumi-kubernetes-operator
    app.kubernetes.io/managed-by: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulumi-kubernetes-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulumi-kubernetes-operator
    spec:
      serviceAccountName: pulumi-kubernetes-operator
      containers:
        - name: operator
          image: pulumi/pulumi-kubernetes-operator:v0.4.0
          imagePullPolicy: IfNotPresent
          args:
            - --zap-level=info
            - --zap-encoder=json
          env:
            - name: WATCH_NAMESPACE
              value: "" # Watch all namespaces
            - name: OPERATOR_NAME
              value: pulumi-kubernetes-operator
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulumi-kubernetes-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - pulumi.com
    resources:
      - stacks
      - stacks/status
      - stacks/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulumi-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pulumi-kubernetes-operator
subjects:
  - kind: ServiceAccount
    name: pulumi-kubernetes-operator
    namespace: pulumi-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stacks.pulumi.com
spec:
  group: pulumi.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectRepo:
                  type: string
                branch:
                  type: string
                repoDir:
                  type: string
                stack:
                  type: string
                config:
                  type: object
                envRefs:
                  type: object
                secretsRef:
                  type: object
                backend:
                  type: string
                refresh:
                  type: boolean
                continueResyncOnCommitMatch:
                  type: boolean
                resyncFrequencySeconds:
                  type: integer
                retryOnUpdateConflict:
                  type: boolean
                destroyOnFinalize:
                  type: boolean
                resources:
                  type: object
            status:
              type: object
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: stacks
    singular: stack
    kind: Stack
