#!/usr/bin/env bash
set -euo pipefail

CACHE_DIR="${1:-/mnt/nvme/hf-cache}"

echo "[hf-cache] Ensuring cache directory at ${CACHE_DIR}"
sudo mkdir -p "${CACHE_DIR}"
sudo chown "$(id -u):$(id -g)" "${CACHE_DIR}"

PROFILE_D_DIR="/etc/profile.d"
PROFILE_FILE="${PROFILE_D_DIR}/huggingface.sh"

echo "[hf-cache] Writing ${PROFILE_FILE} with HF_HOME"
sudo mkdir -p "${PROFILE_D_DIR}"
sudo tee "${PROFILE_FILE}" >/dev/null <<EOF
# Automatically generated by configure-hf-cache.sh
export HF_HOME=${CACHE_DIR}
export HF_HUB_CACHE=\${HF_HOME}/hub
export HUGGINGFACE_HUB_CACHE=\${HF_HOME}/hub
EOF

if [[ -n "${TRANSFORMERS_CACHE:-}" ]]; then
  echo "[hf-cache] Detected TRANSFORMERS_CACHE in current shell. Unset it to avoid deprecation warnings:"
  echo "  unset TRANSFORMERS_CACHE"
fi

echo "[hf-cache] Done. Re-log or run 'source ${PROFILE_FILE}' so HF_HOME is active."
