---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-node
  namespace: tailscale-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-node
rules:
  # Allow reading nodes for hostname/IP discovery
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-node
subjects:
  - kind: ServiceAccount
    name: tailscale-node
    namespace: tailscale-system
---
# Exit node configuration (runs ONLY on tethys)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale-exit-node
  namespace: tailscale-system
  labels:
    app: tailscale-exit-node
spec:
  selector:
    matchLabels:
      app: tailscale-exit-node
  template:
    metadata:
      labels:
        app: tailscale-exit-node
    spec:
      serviceAccountName: tailscale-node
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        oceanid.node/name: tethys  # Pin to tethys only
      tolerations:
        - operator: Exists  # Tolerate any taints
      initContainers:
        # Enable IP forwarding on host
        - name: sysctler
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - |
              sysctl -w net.ipv4.ip_forward=1
              sysctl -w net.ipv6.conf.all.forwarding=1
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.78.3  # Pinned version
          imagePullPolicy: IfNotPresent
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
            - name: TS_KUBE_SECRET
              value: ""  # Don't use k8s secret for state (use hostPath)
            - name: TS_USERSPACE
              value: "false"  # Use kernel networking
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_SOCKET
              value: /var/run/tailscale/tailscaled.sock
            - name: TS_EXTRA_ARGS
              value: "--advertise-exit-node --advertise-routes=10.42.0.0/16,10.43.0.0/16 --accept-routes --accept-dns"
            - name: TS_TAILSCALED_EXTRA_ARGS
              value: "--statedir=/var/lib/tailscale --socket=/var/run/tailscale/tailscaled.sock"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_MODULE
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: tailscale-state
              mountPath: /var/lib/tailscale
            - name: tailscale-socket
              mountPath: /var/run/tailscale
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "tailscale status 2>&1 | grep -q 'Health check:'"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "tailscale status --json | grep -q '\"BackendState\":\"Running\"'"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: tailscale-state
          hostPath:
            path: /var/lib/tailscale-exit
            type: DirectoryOrCreate
        - name: tailscale-socket
          hostPath:
            path: /var/run/tailscale-exit
            type: DirectoryOrCreate
---
# Worker node configuration (runs on all nodes EXCEPT tethys)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale-worker
  namespace: tailscale-system
  labels:
    app: tailscale-worker
spec:
  selector:
    matchLabels:
      app: tailscale-worker
  template:
    metadata:
      labels:
        app: tailscale-worker
    spec:
      serviceAccountName: tailscale-node
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              # Run on all nodes EXCEPT tethys
              - matchExpressions:
                  - key: oceanid.node/name
                    operator: NotIn
                    values:
                      - tethys
      tolerations:
        - operator: Exists  # Tolerate any taints
      initContainers:
        # Enable IP forwarding on host
        - name: sysctler
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - /bin/sh
            - -c
            - |
              sysctl -w net.ipv4.ip_forward=1
              sysctl -w net.ipv6.conf.all.forwarding=1
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.78.3  # Pinned version
          imagePullPolicy: IfNotPresent
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
            - name: TS_KUBE_SECRET
              value: ""  # Don't use k8s secret for state (use hostPath)
            - name: TS_USERSPACE
              value: "false"  # Use kernel networking
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_SOCKET
              value: /var/run/tailscale/tailscaled.sock
            - name: TS_EXTRA_ARGS
              value: "--exit-node=srv712429 --exit-node-allow-lan-access --accept-routes --accept-dns"
            - name: TS_TAILSCALED_EXTRA_ARGS
              value: "--statedir=/var/lib/tailscale --socket=/var/run/tailscale/tailscaled.sock"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_MODULE
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
            - name: tailscale-state
              mountPath: /var/lib/tailscale
            - name: tailscale-socket
              mountPath: /var/run/tailscale
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "tailscale status 2>&1 | grep -q 'Health check:'"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "tailscale status --json | grep -q '\"BackendState\":\"Running\"'"
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: tailscale-state
          hostPath:
            path: /var/lib/tailscale-worker
            type: DirectoryOrCreate
        - name: tailscale-socket
          hostPath:
            path: /var/run/tailscale-worker
            type: DirectoryOrCreate
